application: members-enxo
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

# Application static resources

- url: /styles
  static_dir: dist/styles

- url: /scripts
  static_dir: dist/scripts

- url: /views
  static_dir: dist/views

- url: /images
  static_dir: dist/images

- url: /fonts
  static_dir: dist/fonts

- url: .*
  script: dist/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*
- ^app/.*
- ^\.idea$